default_language_version:
  python: python3.10

repos:

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
      args: ["--profile", "black"]
      files: \.py$

  - repo: https://github.com/myint/autoflake
    rev: v2.0.1
    hooks:
    - id: autoflake
      args: [
        --ignore-init-module-imports,
        --in-place,
        --remove-unused-variables,
        --remove-all-unused-imports,
      ]
      exclude: "tests"

  # - repo: https://github.com/psf/black
  #   rev: 23.1.0
  #   hooks:
  #   - id: black
  #     args: [--config=./pyproject.toml]

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.0.1
  #   hooks:
  #   - id: mypy
  #     additional_dependencies: [
  #       types-PyYAML,
  #       types-pytz,
  #       types-requests,
  #       types-retry,
  #     ]
  #     args: [--config-file=./pyproject.toml]

  # - repo: https://github.com/pycqa/pydocstyle
  #   rev: 6.3.0
  #   hooks:
  #   - id: pydocstyle
  #     additional_dependencies: [ 'tomli']
  #     args: ['--ignore=D213,D203,D204,D416']

  # - repo: local
  #   hooks:
  #   - id: pycodestyle
  #     name: pycodestyle
  #     entry: pycodestyle
  #     language: system
  #     args: [
  #       '--exclude=*init*,test_*.py',
  #       '--ignore=E722,E126,W503',
  #       '--max-line-length=79',
  #     ]
  #     files: \.py$

  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.4
  #   hooks:
  #   - id: bandit
  #     args: ['--skip=B324,B501']
  #     exclude: tests/

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
    - id: mdformat
      args: ['--number']
      exclude: .gitlab

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
      exclude: ^.gitlab/
    - id: end-of-file-fixer
      exclude: ^.gitlab/
    - id: check-yaml
      args: [--allow-multiple-documents]
    - id: check-added-large-files
    - id: detect-private-key
    - id: no-commit-to-branch
      args: ['--branch', 'main']
